### ISSUE TITLE
Embedding broken due to CSP

### ISSUE THREAD

**Issue by riffraff** [bluejeans/embed#3]
As of August 2019, this does not work as bluejeans.com has set security headers to restrict the domains that can embed an iframe, which in turn means no unlisted website can put an iframe around bluejeans, which breaks embedding.

**Comment by glenninn** [comment]
Gabriele,
   Yes you are correct.  BlueJeans is requiring partners who invoke BlueJeans from an iframe to have whitelisted domains.  
If you are impacted, let me/us know and we will add you to the whitelist.

-Glenn

**Comment by riffraff** [comment]
thanks, I suggest you should mention this in the README.

**Comment by glenninn** [comment]
Done... I added commentary regarding whitelisting.
